
---
language: python
python: "2.7"
env:
  - ANSIBLE_VERSION=1.8
before_install:
 - sudo apt-get update --assume-yes -qq
 - sudo apt-get install --assume-yes -qq python-apt python-pycurl
install:
  # Install Ansible.
  - sudo pip install ansible==$ANSIBLE_VERSION

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Install dependencies.
  #- ansible-galaxy install silpion.util
  - git clone https://github.com/silpion/ansible-util.git silpion.util

script:
 - ansible --version
 - ansible-playbook --inventory-file tests/hosts --syntax-check tests/playbook.yml
 - ansible-playbook --inventory-file tests/hosts --connection=local -vvvv tests/playbook.yml
